[build]
  command = "vite build"
  publish = "/dist"
  base ="/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.html"
    [headers.values]
      Cache-Control = "no-store"
